//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkAnew.BundledBroker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimDetail
    {
        public int ClaimDetailsId { get; set; }
        public int FacilityId { get; set; }
        public int ClaimId { get; set; }
        public int ResidentId { get; set; }
        public Nullable<int> RowTypeId { get; set; }
        public Nullable<int> RevenueCodeId { get; set; }
        public string FacilityCode { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> UnitCharge { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalCharge { get; set; }
        public Nullable<decimal> RoutineCosts { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> CostOfServices { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<decimal> RugRate { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual RevenueCode RevenueCode { get; set; }
        public virtual RowType RowType { get; set; }
        public virtual Claim Claim { get; set; }
    }
}
