//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkAnew.BundledBroker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Claim()
        {
            this.ClaimDetails = new HashSet<ClaimDetail>();
            this.Episodes = new HashSet<Episode>();
        }
    
        public int ClaimId { get; set; }
        public int FacilityId { get; set; }
        public int ResidentId { get; set; }
        public long ClaimControlNumber { get; set; }
        public string BillType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalIncome { get; set; }
        public Nullable<decimal> TotalExpenses { get; set; }
        public Nullable<decimal> GainLoss { get; set; }
        public Nullable<int> ClaimTypeId { get; set; }
        public string PayerName { get; set; }
        public Nullable<int> DRGCodeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimDetail> ClaimDetails { get; set; }
        public virtual ClaimType ClaimType { get; set; }
        public virtual DRGCode DRGCode { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual Resident Resident { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Episode> Episodes { get; set; }
    }
}
