//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkAnew.BundledBroker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityPullData
    {
        public int FacilityPullDataId { get; set; }
        public int FacilityId { get; set; }
        public Nullable<int> DRG { get; set; }
        public Nullable<System.DateTime> LastDateOfPull { get; set; }
        public Nullable<long> LastClaimControlNumber { get; set; }
    
        public virtual Facility Facility { get; set; }
    }
}
