//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkAnew.BundledBroker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedResult
    {
        public long OrderedResultId { get; set; }
        public int SessionId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> RevenueCodeId { get; set; }
        public Nullable<int> DRG { get; set; }
        public string Residentname { get; set; }
        public string HICNumber { get; set; }
        public string BillType { get; set; }
        public string FromDate { get; set; }
        public string ENdDate { get; set; }
        public string RevenueCode { get; set; }
        public string ItenDescription { get; set; }
        public string UnitCharge { get; set; }
        public string Quantity { get; set; }
        public string TotalCharge { get; set; }
        public string RoutineCosts { get; set; }
        public string WorksheetC { get; set; }
        public string CostofServices { get; set; }
        public string TotalIncome { get; set; }
        public string SummaryTitle { get; set; }
        public Nullable<decimal> SummaryAmount { get; set; }
        public string RowType { get; set; }
        public Nullable<int> ClaimRowNumber { get; set; }
        public Nullable<int> ReportRowNumber { get; set; }
        public Nullable<long> ClaimControlNumber { get; set; }
        public string PayerName { get; set; }
    }
}
