//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkAnew.BundledBroker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resident()
        {
            this.Claims = new HashSet<Claim>();
            this.Episodes = new HashSet<Episode>();
        }
    
        public int ResidentId { get; set; }
        public int FacilityId { get; set; }
        public int ResidentNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HICNumber { get; set; }
        public Nullable<int> ModelTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Episode> Episodes { get; set; }
        public virtual Facility Facility { get; set; }
        public virtual ModelType ModelType { get; set; }
    }
}
