//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkAnew.BundledBroker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueCodeMultiplier
    {
        public int RevenueCodeMultiplierId { get; set; }
        public int FacilityId { get; set; }
        public int RevenueCodeId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public decimal Multiplier { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual RevenueCode RevenueCode { get; set; }
    }
}
