//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkAnew.BundledBroker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USCounty
    {
        public int USCountiesId { get; set; }
        public int StateId { get; set; }
        public string CountyName { get; set; }
    
        public virtual State State { get; set; }
    }
}
